apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: akhq-operator
  labels:
    strimzi.io/cluster: cmc-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - operation: All
        resource:
          name: '*'
          type: group
      - operation: All
        resource:
          name: '*'
          type: topic
      - operation: All
        resource:
          type: cluster
