logLevel: DEBUG

extraEnvs:
  - name: KUBERNETES_BACKWARDSCOMPATIBILITYINTERCEPTOR_DISABLE
    value: "true"

resources:
  limits:
    memory: 500Mi
    cpu: 1000m
  requests:
    memory: 500Mi
    cpu: 200m